spring:
   profiles:
      active: develop

---
spring:
   profiles: develop
   data:
     elasticsearch:
      # 必须先访问9200端口确定cluster-name,因为安装/启动方式不一样，其cluster-name也不一样
       cluster-name: elasticsearch
       cluster-nodes: 127.0.0.1:9300
       properties:
         path:
           logs: ./elasticsearch/log
           data: ./elasticsearch/data
       repositories:
         enabled: true
   cache:
     jcache:
       config: classpath:ehcache.xml


blog-system:
  markdown-file-base: ${HOME}/markdown-blog/
  markdown-file-watch-service:
    enabled: true
  link-accessibility-validator:
    enabled: false
    cron: "0 0 0 * * ?"
  index-page:
    seo-keywords-zh: "个人博客,技术博客,博客系统,markdown博客"
    seo-keywords-en: "IT Blog,Blog System"
    seo-descriptions:
      - "首页摘要"
      - "another description"
      - "more description is allowed"
    display-title: "网站名 | 你喜欢展示的其他名称"
    record-code: "备案号"
    contact: "电话 / 邮箱"

  page-view-times:
    sync-duration-seconds-threshold: 20000

  seo:
    site-map:
      store-dir: ${HOME}/blog-site-map/
      cron: "0 0 0 * * ?"
      server-url: http://localhost:8080
  blog-document-crud-admin:
    user-name: admin
    user-password: password


server:
   port: 8443
   ssl:
     key-alias: tomcat
     key-password: 123456
     key-store-password: 123456
     key-store: classpath:keystore.p12
     key-store-type: JKS
     enabled: false

http:
  with-https:
    enabled: false
  port: 8080


