spring:
   profiles:
      active: develop

---
spring:
   profiles: develop
   data:
     elasticsearch:
       cluster-name: elasticsearch
       cluster-nodes: 127.0.0.1:9300
       properties:
         path:
           logs: ./elasticsearch/log
           data: ./elasticsearch/data

blog.git.base: "/home/calvin/data/markdown-blog/blog/"
markdown-file-base: "/home/calvin/data/markdown-blog/blog/"

blog-system:
  link-accessibility-validator:
    enabled: true
  index-page:
    seo-keywords-zh: "个人博客,技术博客,博客系统,markdown博客"
    seo-keywords-en: "IT Blog,Blog System"
    seo-descriptions:
      - "a description in English"
      - "another description"
      - "more description is allowed"
    display-title: "title display in web page"
    record-code: "a recode code in is needed"
    contact: "your email or phone number"

seo:
   site-map:
      store-dir: /home/calvin/blog-site-map/
server:
   port: 8080






