spring:
   profiles:
      active: develop

---
spring:
   profiles: develop
blog.git.base: "/home/calvin/data/markdown-blog/blog/"
markdown-file-base: "/home/calvin/data/markdown-blog/blog/"
seo:
   site-map:
      store-dir: /home/calvin/blog-site-map/
server:
   port: 8080

